### ISSUE TITLE
Aya Neo 2021 R5 4500u DSDT override failure

### ISSUE THREAD

**Issue by mivlives4ever** [ChimeraOS/device-quirks#58]
Aya Neo 2021 R5 4500u 512GB, installed fresh ChimeraOS 43 with advanced install, and applying the overrides with sudo frzr-tweaks, it produces this: 

AYADEVICE does not have any supported models. Exiting.

-------------------

BIOS shows version V1.22_P3COM43
Manufacturer Name: AYADEVICE
Product Name: AYA NEO FOUNDER

What other info is needed to get this added to the database of "fixed" DSDTs?

**Comment by pastaq** [comment]
run these commands and upload the `dsdt.dsl` that is generated.

```
sudo frzr-unlock
sudo pacman -S acpica
sudo cat /sys/firmware/acpi/tables/DSDT > dsdt.dat
iasl -d dsdt.dat
```

Also, run this command to get your DMI data so we can add a match for your device and upload the `dmi_data` file that is generated.
`for f in /sys/class/dmi/id/*; do echo "$f:"; sudo cat $f; done > dmi_data`

**Comment by mivlives4ever** [comment]
Ran commands and attached resulting dsdt.dsl and dmi_data, zipped
[DSDT_DMIDATA.zip](https://github.com/ChimeraOS/device-quirks/files/12009157/DSDT_DMIDATA.zip)

**Comment by pastaq** [comment]
To test:
```
sudo frzr-unlock
git clone https://github.com/ChimeraOS/device-quirks.git && cd device_quirks
sudo cp -r usr/ /
sudo frzr-tweaks
```
If it builds your DSDT then `reboot` and run `lsmod | grep bmi`, you should see the bmi160 drivers loaded.

**Comment by mivlives4ever** [comment]
ok, i get this:

[gamer@chimeraos ~]$ sudo frzr-unlock
[sudo] password for gamer: 
frzr deployment chimeraos-43_6978095 unlocked
[gamer@chimeraos ~]$ git clone https://github.com/ChimeraOS/device-quirks.git && cd device-quirks
Cloning into 'device-quirks'...
remote: Enumerating objects: 1296, done.
remote: Counting objects: 100% (553/553), done.
remote: Compressing objects: 100% (232/232), done.
remote: Total 1296 (delta 319), reused 456 (delta 264), pack-reused 743
Receiving objects: 100% (1296/1296), 363.61 KiB | 6.49 MiB/s, done.
Resolving deltas: 100% (498/498), done.
[gamer@chimeraos device-quirks]$ git checkout pastaq/aya_founders_dsdt
branch 'pastaq/aya_founders_dsdt' set up to track 'origin/pastaq/aya_founders_dsdt'.
Switched to a new branch 'pastaq/aya_founders_dsdt'
[gamer@chimeraos device-quirks]$ sudo cp -r usr/ /
[gamer@chimeraos device-quirks]$ sudo frzr-tweaks
Checking for device-quirks
AYADEVICE does not have any supported models. Exiting.
[gamer@chimeraos device-quirks]$

**Comment by pastaq** [comment]
Ah shoot, I forgot to add the DMI match for AYADEVICE into the ayaneo script.

**Comment by pastaq** [comment]
Alright, updated to include AYADEVICE.
```
git pull 
sudo cp -r usr/ /
sudo frzr-tweaks
```

**Comment by mivlives4ever** [comment]
Yes that worked! 
and now i get this:

[gamer@chimeraos ~]$ lsmod | grep bmi
bmi160_spi             16384  0
bmi160_i2c             16384  0
bmi160_core            20480  2 bmi160_i2c,bmi160_spi
industrialio_triggered_buffer    16384  1 bmi160_core
industrialio          126976  4 industrialio_triggered_buffer,cm32181,kfifo_buf,bmi160_core
[gamer@chimeraos ~]$

**Comment by pastaq** [comment]
Awesome, looks like it worked. I'll merge this in
