### ISSUE TITLE
Update PKGBUILD

### ISSUE THREAD

**Issue by pastaq** [ChimeraOS/device-quirks#6]
The following things need to be added to the PKGBUILD:

install [/usr/lib/udev/hwdb.d/61-sensor-local.hwbd](https://github.com/ChimeraOS/device-quirks/blob/main/usr/lib/udev/hwdb.d/61-sensor-local.hwbd)
install [/usr/lib/systemd/system/ryzen-tctl.service](https://github.com/ChimeraOS/device-quirks/blob/main/usr/lib/systemd/system/ryzen-tctl.service)
python install /ryzen_tctl

After #5 is merged:
install [/usr/lib/systemd/user/aya-air-audio.service](https://github.com/ChimeraOS/device-quirks/blob/air-audio/usr/lib/systemd/user/aya-air-audio.service)
install [/usr/bin/device-quirks/aya-neo-air-audio-phase-fix](https://github.com/ChimeraOS/device-quirks/blob/air-audio/usr/bin/device-quirks/aya-neo-air-audio-phase-fix)
add [swh-plugins](https://archlinux.org/packages/?name=swh-plugins) as a dependency

**Comment by Samsagax** [comment]
PKGBUILD updated.
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=chimeraos-device-quirks-git

I'm closing this one up but will transfer teh comment for #5
