### ISSUE TITLE
Firmware override issue ROG Ally

### ISSUE THREAD

**Issue by FLA5H-io** [ChimeraOS/device-quirks#65]
Issue with firmware overrides on ROG Ally.

Running sudo frzr-tweaks ends up outputting 

“Unable to find matching DSDT patch. Firmware override skipped” 

bios is 323

**Comment by pastaq** [comment]
I just added support for that BIOS a few hours ago. You'll need to wait for the next ChimeraOS update or manually update the device-quirks package

**Comment by FLA5H-io** [comment]
How would you go about updating it manually? I was also on an older version before this getting the same error.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by pastaq** [comment]
```
sudo frzr-unlock
sudo pikaur -Syu chimeraos-device-quirks-git
```

**Comment by WarlockLord** [comment]
pastaq you were helping me on discord. My checksum doesn't match what you posted for 323.

**Comment by pastaq** [comment]
> pastaq you were helping me on discord. My checksum doesn't match what you posted for 323.

What is your checksum?

**Comment by WarlockLord** [comment]
0xE8

**Comment by FLA5H-io** [comment]
What bios revisions are support with the current build, I couldn’t find a list.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ashtophet** [comment]
Is this possible, @pastaq ?

@FLA5H-io can you post the output of:
`cat /sys/class/dmi/id/bios_version`

and upload your DSL file?
`cat /sys/firmware/acpi/tables/DSDT > system-dumped-dsdt.dat && iasl -d system-dumped-dsdt.dsl`

Bios 323 here is 0x58, 323 patched is 0x38

**Comment by FLA5H-io** [comment]
I can post this over the next few days. I work 12 hour shifts, but I’ll give this a whirl over my weekend end the next few days.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by davnozdu** [comment]
> sudo frzr-unlock
> sudo pikaur -Syu chimeraos-device-quirks-git

Thanks, it is resolve this problem.
But on update I am get several error, but after reboot sound start to work

**Comment by FLA5H-io** [comment]
Interesting, mine still didn’t work after running that.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by davnozdu** [comment]
> Interesting, mine still didn’t work after running that. Get Outlook for iOS<https://aka.ms/o0ukef>
> […](#)

I am try update several times and get 2 or 3 error but I am skip this error and continue and without successful.
Then I am come to work and try again and after start sound start to work.
Maybe Chimera team make hotfix (then OS start chimeraos system check and download config update)

**Comment by davnozdu** [comment]
> Interesting, mine still didn’t work after running that. Get Outlook for iOS<https://aka.ms/o0ukef>
> […](#)

This bug already fixed 

[usr/share/device-quirks/scripts/asus/ally/ally.sh](https://github.com/ChimeraOS/device-quirks/commit/fa9d1174b76ee11f81b4de8061781d1d54915238)

**Comment by pastaq** [comment]
Firmware overrides are no longer required for the ROG Ally
