### ISSUE TITLE
Unable to enable frzr tweeks

### ISSUE THREAD

**Issue by ripplingsnake** [ChimeraOS/device-quirks#74]
Hello I tired the sudo command but it says frzr overrides are disabled.
I navigated to the configuration file but it says I don’t have permission to open it or change it.
I am new to Linux so have no idea how to change this 
Thanks

**Comment by pastaq** [comment]
You need to use `sudo` when opening the file

Eg,  in a terminal:
`sudo nano /etc/device-quirks/device-quirks.conf`
