### ISSUE TITLE
If do not override using dsdt, After waking up from hibernation, Rog Ally has no sound

### ISSUE THREAD

**Issue by honjow** [ChimeraOS/device-quirks#82]
I use a swap partition for hibernation. When I just woke up, the sound is normal, but after a while, the sound disappears. After testing, I found that if I restore using the dsdt override, this issue does not occur. Here are some logs I found using 'journalctl -b -k' after hibernation and wake-up
```
9月 15 23:24:30 Ally kernel: cs35l41-hda i2c-CSC3551:00-cs35l41-hda.0: System Resume not supported
...
9月 15 23:24:46 Ally kernel: cs35l41-hda i2c-CSC3551:00-cs35l41-hda.0: Failed to set mailbox cmd 1 (status 0)
9月 15 23:24:46 Ally kernel: cs35l41-hda i2c-CSC3551:00-cs35l41-hda.1: Failed to set mailbox cmd 1 (status 0)
```
Because of this issue, I had to enable dsdt override again.

**Comment by pastaq** [comment]
What OS/kernel are you on?

**Comment by honjow** [comment]
> What OS/kernel are you on?

chimeraos, the kernel is linux-chimeraos-6.5.3.chos1-1

**Comment by honjow** [comment]
I accidentally discovered that Ally's voice is affected by the startup animation sound effect switch in the BIOS settings.
After multiple tests by me,
- If the startup sound effect is enabled and DSDT override is enabled, there will be no sound when entering the system.
- If the startup sound effect is enabled and DSDT override is not used, the sound will be normal when entering the system, but after waking up from hibernate, the sound will be lost, and the journalctl information is as follows:
```
10月 03 23:42:30 Ally kernel: cs35l41-hda i2c-CSC3551:00-cs35l41-hda.0: System Resume not supported
...
10月 03 23:42:48 Ally kernel: cs35l41-hda i2c-CSC3551:00-cs35l41-hda.0: Failed to lock test key: -121
10月 03 23:42:48 Ally kernel: cs35l41-hda i2c-CSC3551:00-cs35l41-hda.1: Failed to lock test key: -121
10月 03 23:42:48 Ally kernel: cs35l41-hda i2c-CSC3551:00-cs35l41-hda.0: Failed to write MBOX: -121
10月 03 23:42:48 Ally kernel: cs35l41-hda i2c-CSC3551:00-cs35l41-hda.1: Failed to write MBOX: -121
10月 03 23:44:24 Ally kernel: cs35l41-hda i2c-CSC3551:00-cs35l41-hda.0: Failed to write MBOX: -121
10月 03 23:44:24 Ally kernel: cs35l41-hda i2c-CSC3551:00-cs35l41-hda.1: Failed to write MBOX: -121

```

- If you turn off the startup sound and don't use DSDT override, the sound works fine when entering the system, but after waking up from hibernate, the sound is lost. This is the situation described at the beginning.

- The last combination is to turn off the startup sound and use DSDT override. The startup sound is normal, and the sound is normal after waking up from sleep.

---
Test system chimeraos,  kernel linux-chimeraos-6.5.5

**Comment by pastaq** [comment]
Wild

**Comment by pastaq** [comment]
Sorry, I'm just blown away about how stupid the ACPI configuration is for this device.

Are you using hybernate and sleep interchangeably or does this only affect hybernate and not sleep?

**Comment by honjow** [comment]
> Sorry, I'm just blown away about how stupid the ACPI configuration is for this device.
> 
> Are you using hybernate and sleep interchangeably or does this only affect hybernate and not sleep?

I'm sure it only affect hybernate and not sleep.I created a swap partition and added 'resume' in the kernel parameters to implement hibernation. Because using sleep with Ally easily leads to the issue of 'Asus Keyboard' getting lost, I can avoid this problem with hibernation.
