### ISSUE TITLE
Unable to do firmware overide after enabling on ROG Ally

### ISSUE THREAD

**Issue by Ochoartu** [ChimeraOS/device-quirks#92]
I updated my ROG Ally's UEFI to version 335 and installed ChimeraOS on it.  No sound is coming from it and i enabled the necessary file to get audio. When i typed in 'sudo frzr-tweaks' it comes back with 'ASUSTek COMPUTER INC. does not have any supported models. Exiting.'

**Comment by CapitaineJSparrow** [comment]
Same here

**Comment by pastaq** [comment]
DSDT overrides are no longer required for the ROG Ally. However, you will need to use the `testing` image as the kernel patch  that fixes audio on BIOS 330+ isn't included in v44-1.

**Comment by Ochoartu** [comment]
Alright! how do i do that, if i may ask? is there a link to a wiki i can use?

**Comment by pastaq** [comment]
Firmware overrides are no longer required on the ROG Ally
